version: "3.7"

services:
    node: &node
        build: node
        init: true
        working_dir: /app
        volumes:
            - ../../:/app

    app:
        <<: *node
        command: yarn start:app
        expose:
            - 3000
        ports:
            - "${EXPOSED_APP_PORT}:3000"

    server:
        <<: *node
        command: yarn start:dev
        volumes:
            - ../../api:/app
        expose:
            - 3001
        ports:
            - "${EXPOSED_SERVER_PORT}:3001"
